<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/vendor/bootstrap.min.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/vendor/slick.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/vendor/slick-theme.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/sal.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/feather.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/fontawesome.min.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/euclid-circulara.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/swiper.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/magnify.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/odometer.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/animation.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/bootstrap-select.min.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/jquery-ui.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/plugins/magnigy-popup.min.css">
<link rel="stylesheet" href="{{asset('/frontend/')}}/assets/css/style.css">
